config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#index'

  # ゲストログイン用アクション
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  # sign_upでエラーが出た後、リロードでのエラー回避
    get 'users', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  # get 'users/mypage' => 'users#show'
  # get 'users/unsubscribe' => 'users#unsubscribe'
  # get 'recipes/search' => 'recipes#search'
  # patch 'users/withdraw' => 'users#withdraw'

  resources :users, only:[:edit,:update] do
    collection do
      get :mypage, action: :show
      get :unsubscribe
      patch :withdraw
    end
  end

  resources :recipes, only:[:new,:index,:show,:edit,:create,:update,:destroy] do
    collection do
      get :bookmarks
      get :search
    end
  end

  resources :units, only:[:index,:create,:destroy]
  resources :genres, only:[:index,:create,:destroy]
  resources :bookmarks, only:[:create,:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image
  # ネストしたフォームにバリデーションをかける
  validates_associated :ingredients
  validates_associated :steps
  
  validates :cuisine_name, presence: true
  validates :quantity, presence: true
  validates :ingredients, presence: true
  validates :steps, presence: true

  belongs_to :user
  belongs_to :genre

  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_recipes, through: :bookmarks, source: :user

# ネストしたフォームへ
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
  has_many :materials
  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :all_blank
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank


  # def bookmarked_by?(user)
  #   bookmarks.where(user_id: user).exists?
  # end

# 栄養素の計算式
  def calculate(column, recipe)
    # p "==========================================="
    # p "start"
    return_value = 0
    recipe.ingredients.each do |ing|
      next unless ing.material_id
      materials_sum = ing.material["#{column}"]
      # p "column: #{column}"
      # p "name: #{ing.material.name}"
      # p "materials_sum: #{materials_sum}"
      # 単位による条件分岐
      materials_amount = 0
      convert_amount = 0
      if ing.unit == ('g'||'cc'||'ml')
        materials_amount = ing.amount.to_f
      elsif ing.unit == 'kg'
        materials_amount = (ing.amount.to_f) * 1000
      elsif ing.unit == 'mg'
        materials_amount = (ing.amount.to_f) * 0.001
      else
        unit = Unit.find_by(material_id: ing.material_id, unit: ing.unit)
        if unit
          convert_amount = (unit.g * ing.amount.to_f)
          # p "convert_amount: #{convert_amount}"
        else
        end
      end

      # p "total materials_sum: #{materials_sum}"
      # p "total convert_amount: #{convert_amount}"
      ret = ((materials_sum / 100) * (convert_amount + materials_amount))
      # p "ret: #{ret}"
      return_value += ret
    end
    # p "return_value: #{return_value}"
    # p "==========================================="
    return_value.floor(1)
  end


  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_img.png')
      image.attach(io: File.open(file_path), filename: 'default-image.png', content_type: 'image/png')
    end
   # byebug
    image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, only: [:new,:edit,:create,:update,:destroy]
  before_action :set_recipe, only: [:show,:edit,:update,:destroy]

  def new
    @recipe = Recipe.new
    @genres = Genre.all
    @materials = Material.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    # GoogleCloudVisionAPI用の記述
    # if recipe_params[:image]
    #   Vision.get_image_data(recipe_params[:image]) # or params[:recipe][:image]
    #   @recipe.save
    #   count = params[:recipe][:material_count].to_i
    #   Ingredient.order('id DESC').limit(count).each do |ing|
    #     material = Material.find_by(name: ing.name)
    #     ing.update(material_id: material.id)
    #   end
    #   redirect_to edit_recipe_path(@recipe)
    if @recipe.save
      count = params[:recipe][:material_count].to_i
      Ingredient.order('id DESC').limit(count).each do |ing|
        material = Material.find_by(name: ing.name)
        if material
          ing.update!(material_id: material.id)
        end
      end
      redirect_to recipes_path, notice: "レシピを登録しました。"
    else
      flash.now[:notice] = "記入の漏れがあります。"
      @materials = Material.all
      render :new
    end
  end

  def index
    if user_signed_in?
      @recipes = Recipe.includes([:user],[:bookmarks]).where(user_id: current_user.id).order(created_at: :desc)
    else
      @recipes = Recipe.all
    end
  end

  def show
    @title = "#{@recipe.cuisine_name}"
    @calorie = @recipe.calculate(:calorie, @recipe).floor(0)
    @protein = @recipe.calculate(:protein, @recipe)
    @lipid = @recipe.calculate(:lipid, @recipe)
    @carbohydrate = @recipe.calculate(:carbohydrate, @recipe)
    @salt = @recipe.calculate(:salt, @recipe)
  end

  def search
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).page(params[:page]).per(6)
    @search = params[:q][:cuisine_name_or_ingredients_name_cont]
# 取得したgenre_id_eqをnameに変換
# find_byでカラムから探す。tryでエラーではなくnilを返す
    @search_genre = Genre.find_by(id: params[:q][:genre_id_eq]).try(:name)
  end


  def edit
    @title = "#{@recipe.cuisine_name}の編集"
    @materials = Material.all
    @genres = Genre.all
    if @recipe.user == current_user
      render :edit
    else
      redirect_back fallback_location: root_path, flash: { alert: "他人のレシピは編集できません" }
    end
  end

  def update
    if @recipe.update(recipe_params)
    @recipe.ingredients.each do |ing|
      material = Material.find_by(name: ing.name)
      if material
        ing.update!(material_id: material.id)
      else
        ing.update!(material_id: nil)
      end
    end
      redirect_to recipe_path(@recipe), flash: { notice: "「#{@recipe.cuisine_name}」のレシピを更新しました。" }
    else
      flash.now[:notice] = "記入の漏れがあります。"
      redirect_back fallback_location: recipe_path(@recipe)
    end
  end

  def destroy
    @recipe.destroy!
    redirect_to recipes_path, flash: { notice: "レシピを削除しました。" }
  end


  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end


  def recipe_params
    params.require(:recipe).permit(
      :user_id,
      :cuisine_name,
      :quantity,
      :genre_id,
      :image,
      ingredients_attributes: [:id, :name, :unit, :amount, :_destroy],
      steps_attributes: [:id, :direction, :_destroy]
    )
  end

end

app/views/recipes/_ingredient_fields.html.erb
<!--材料のフォーム-->
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <div class="ingredient_input row">
<!--データリストでmaterialテーブルからのフォーム-->
    <%= f.text_field :name, id: "js-text-field", list: "arealists", class:"form-control offset-3 col-3 border-top-0 border-left-0 border-right-0 border-warning" %>
      <datalist id="arealists">
        <%= options_for_select(@materials.map{ |material| [material.name] }) %>
      </datalist>
<!--分量の入力フォーム-->
    <%= f.text_field :amount, placeholder:"分量", class:"quantity form-control col-3 border-top-0 border-left-0 border-right-0 border-warning" %>
    <%= f.select :unit, Ingredient.units.keys.to_a, {}, class:"form-control col-2 border-top-0 border-left-0 border-right-0 border-warning" %>

    <%= link_to '#', class:"remove-field-btn" do %>
      <%= image_tag 'delete.svg', class:"remove_fields" %>
    <% end %>
  </div>
</div>

app/views/recipes/_step_fields.html.erb
<!--作り方のフォーム-->
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <div class="step_input row">
    <p class="step_number text-right col-3"></p>.
    <%= f.text_area :direction, class:"form-control col-8 border-top-0 border-left-0 border-right-0 border-warning" %>

    <%= link_to '#', class:"remove-field-btn" do %>
      <%= image_tag 'delete.svg', class:"remove_fields" %>
    <% end %>
  </div>
</div>

app/views/recipes/_top.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-12 text-center h2 my-4 font-weight-bold">
      RECIPE　ZUKANへ、ようこそ！<br>
      このサイトは、料理レシピの管理サイトになります。<br>
      レシピの簡単登録はもちろん、主要5つの栄養成分の自動計算や、<br>
      検索・お気に入りに追加など、様々な機能が用意されています。<br>
      ぜひ便利なツールとして、料理のお供にお使いください！
    </div>
  </div>
  <div class="row my-5">
    <div class="d-grid gap-2 col-7 mx-auto my-3">
      <%= link_to "お試しログイン", users_guest_sign_in_path, method: :post, class:"btn btn-lg btn-success mb-4 col-12" %>
      <%= link_to "新規登録", new_user_registration_path, class:"btn btn-lg btn-primary mb-5 col-12" %>
    </div>
  </div>
</div>

app/views/recipes/bookmarks.html.erb
<% if @bookmark_recipes.present? %>
  <%= render "bookmark.index", bookmarks: @bookmarks %>
<% else %>
  <p>お気に入りしたレシピはありません。</p>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/flash' %>

<div class="container my-4">
  <div class="row mx-3 my-4">
    <div class="h2 font-weight-bold"><%= @title %></div>
  </div>
  <%= form_with model: @recipe, url: recipe_path, method: :patch do |f| %>
    <section class="form row h5 border-top border-bottom border-warning border-5">
      <div class="col-5 my-4">
        <h4 class="recipe-form">写真
          <%= f.label :image do %>
            <i class="fas fa-camera"></i>
            <%= f.file_field :image, class: 'preview', style: 'display:none;' %>
          <% end %>
        </h4>
        <%= image_tag @recipe.get_image(450,450), class: "uploader img-fluid ml-3" %>
      </div>

      <div class="offset-1 col-6 my-4">
        <div class="form-group row">
          <%= f.label :"料理名", class:"col-4" %>
          <%= f.text_field :cuisine_name, class:"form-control col-6 border-top-0 border-left-0 border-right-0 border-warning"%>
        </div>
        <div class="form-group row">
          <%= f.label :"出来上がり量", class:"col-4"  %>
          <%= f.text_field :quantity, placeholder:"人前", class:"quantity form-control col-6 border-top-0 border-left-0 border-right-0 border-warning" %>
        </div>
  <!--材料入力フォーム・部分テンプ-->
        <div class="form-group row">
          <div class="col-3">材料</div>
          <i class="fas fa-exclamation-circle text-muted"></i>
          <h6 class="text-muted">食材量の入力はg単位推奨</h6>
        </div>
        <section class="ingredient">
          <%= f.fields_for :ingredients do |ingredient| %>
            <%= render "ingredient_fields", f: ingredient %>
          <% end %>
          <%= link_to_add_fields "《材料の追加》", f, :ingredients%>
        </section>

  <!--作り方入力フォーム・部分テンプ-->
        <div class="form-group row">
          <div class="col-4">作り方</div>
        </div>
        <section class="step my-3">
          <div class="field steps-wrapper">
            <%= f.fields_for :steps do |step| %>
              <%= render "step_fields", f: step %>
            <% end %>
            <%= link_to_add_fields "《作り方の追加》", f, :steps %>
          </div>
        </section>

        <div class="form-group row">
          <%= f.label :"ジャンル", class:"col-4" %>
          <%= f.collection_select :genre_id, @genres, :id, :name, prompt: "選択してください", class:"form-control col-6" %>
        </div>
        <div class="action row my-5">
          <%= f.submit "編集する", class:"offset-4 col-4 btn btn-lg btn-success" %>
        </div>
      </div>
    </section>
  <% end %>

  <div clss="row">
    <div class="col-7 my-5">
      <%= link_to '編集をやめる', recipe_path(@recipe), class:"btn btn-lg btn-primary ml-5"%>
      <%= link_to 'レシピを削除', recipe_path, method: :delete, data: { confirm: "削除してよろしいですか？" }, class:"btn btn-lg btn-danger ml-5"%>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<%= flash[:notice] %>

<% if user_signed_in? %>
  <div class="container my-4">
    <div class="row my-3">
      <div class="h3 font-weight-bold">レシピ一覧</div>
        <table class="table table-hover">
          <% @recipes.each do |recipe| %>
            <tr class="font-weight-bold">
              <td class="col-2">
                <%= image_tag recipe.get_image(100,100), class: "img-fluid ml-3"  %>
              </td>
              <td class="col-10 h3">
                <%= link_to recipe.cuisine_name, recipe_path(recipe.id)%>
              </td>
            </tr>
           <% end %>
        </table>
    </div>
  </div>
<% else %>
  <%= render "top" %>
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/flash' %>

<div class="container my-4">
  <div class="row my-4">
    <div class="h2 font-weight-bold">レシピ登録</div>
  </div>
  <%= form_with model: @recipe, url: recipes_path, method: :post do |f| %>
    <section class="form row h5 border-top border-bottom border-warning border-5">
      <div class="col-5 my-4">
        <h4 class="recipe-form">写真
          <%= f.label :image do %>
            <i class="fas fa-camera"></i>
            <%= f.file_field :image, class: 'preview', style: 'display:none;' %>
          <% end %>
        </h4>
        <%= image_tag 'no_img.png', class: "uploader img-fluid ml-3", :size => '450x450' %>
      </div>

      <div class="offset-1 col-6 my-4">
        <div class="form-group row">
          <%= f.label :"料理名", class:"col-4" %>
          <%= f.text_field :cuisine_name, class:"form-control col-6 border-top-0 border-left-0 border-right-0 border-warning"%>
        </div>
        <div class="form-group row">
          <%= f.label :"出来上がり量", class:"col-4"  %>
          <%= f.text_field :quantity, placeholder:"人前", class:"quantity form-control col-6 border-top-0 border-left-0 border-right-0 border-warning" %>
        </div>
  <!--材料入力フォーム・部分テンプ-->
        <div class="form-group row">
          <div class="col-3">材料</div>
          <div tabindex="0" data-toggle="popover" data-trigger="focus" title="注意事項"
          data-content="野菜などの重さが一定でない食材は、おおよその重さを入力いただかないと、栄養素の計算ができない場合があります。">
            <i class="fas fa-exclamation-circle text-muted"></i>
          </div>
          <h6 class="text-muted">食材量の入力はg単位推奨</h6>
        </div>
        <section class="ingredient my-3">
          <%= f.fields_for :ingredients do |ingredient| %>
            <%= render "ingredient_fields", f: ingredient %>
          <% end %>
          <%= link_to_add_fields "《材料の追加》", f, :ingredients %>
        </section>

  <!--作り方入力フォーム・部分テンプ-->
        <div class="form-group row">
          <div class="col-4">作り方</div>
        </div>
        <section class="step my-3">
          <div class="field steps-wrapper">
            <%= f.fields_for :steps do |step| %>
              <%= render "step_fields", f: step %>
            <% end %>
            <%= link_to_add_fields "《作り方の追加》", f, :steps %>
          </div>
        </section>

        <div class="form-group row">
          <%= f.label :"ジャンル", class:"col-4" %>
          <%= f.collection_select :genre_id, @genres, :id, :name, prompt: "選択してください", class:"form-control col-6" %>
        </div>
        <div class="action row my-5">
          <%= f.hidden_field :material_count, value: '' %>
          <%= f.submit "登録する", class:"offset-4 col-sm-4 btn btn-lg btn-success" %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/recipes/search.html.erb
<div class="container my-4">
  <div class="row my-3">
    <div class="h3 font-weight-bold">検索結果一覧</div>
  </div>

  <% if @search.present? %>
    <div class="row">
      「<%= @search %>」の検索結果
    </div>
    <%= render 'shared/recipe_list' %>

  <% elsif @search_genre.present? %>
    <div class="row">
    「<%= @search_genre %>」の検索結果
    </div>

    <%= render 'shared/recipe_genre' %>
  <% else %>
    <div class="row">
    "該当する検索結果はありません。"
    </div>
  <% end %>

  <%= paginate @recipes %>

  <div class="cancel my-4">
    <%= link_to 'レシピ一覧に戻る', recipes_path %>
  </div>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/flash' %>

<div class="container my-4">
  <div class="row mx-3 mt-3">
    <div class="h2 font-weight-bold"><%= @title %></div>
  </div>
  <div class="row">
    <div class="offset-3 col-3 mb-3">
      <% if current_user.own?(@recipe) %>
        <%= link_to "編集する", edit_recipe_path(@recipe), class:"btn btn-lg btn-primary" %>
      <% else %>
        <%= link_to bookmarks_path(recipe_id: @recipe.id), method: :post, class: 'btn btn-primary' do %>
          <i class="fas fa-clone"></i> お気に入りに登録
   ​    <% end %>
      <% end %>
    </div>
  </div>
  <div class="row border-top border-bottom border-warning border-5">
  <!--ユーザーのみ編集ボタン-->
    <div class="col-5 my-4">
      <!--画像が添付されている時-->
      <div>
        <% if @recipe.image.attached? %>
          <%= image_tag @recipe.get_image(450,450), class: "img-fluid ml-3" %>
        <% end %>
      </div>
    </div>

    <table class="table table-borderless offset-1 col-6 my-4">
      <tbody class="h5">
        <tr>
          <td class="col-3">料理名：</td>
          <td class="col-7"><%= @recipe.cuisine_name %></td>
        </tr>
        <tr>
          <td>出来上がり量：</td>
          <td><%= @recipe.quantity %></td>
        </tr>
        <tr>
          <td>材料：</td>
          <% @recipe.ingredients.each do |ingredient| %>
          <tr>
            <th></th>
            <td><%= ingredient.name %>　<%= ingredient.amount %><%= ingredient.unit %></td>
          </tr>
          <% end %>
        </tr>
        <tr>
          <td>作り方：</td>
          <% @recipe.steps.each_with_index do |step, i| %>
          <!--<#% @recipe.steps.each do |step| %>-->
          <tr>
            <th class ="text-right"><%= "#{i + 1}." %></th>
            <td><%= step.direction %></td>
          </tr>
          <% end %>
        </tr>
        <tr>
          <td>ジャンル：</td>
          <td><%= @recipe.genre.name %></td>
        </tr>
        <!--boolean型はtrueなど必要なし-->
        <tr>
          <% if @recipe.user.status %>
            <td>レシピ作成者：</td>
            <td><%= @recipe.user.nickname %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <!--栄養素の計算表示-->
  <div class="row my-4 border-bottom border-warning border-5">
    <h5>
      <table class="table table-borderless">
        <tr>
          <td><h4 class="bg-warning">栄養成分表</h4></td>
        </tr>
        <tr>
          <td>カロリー：</td><td><%= @calorie %>kcal</td>
        </tr>
        <tr>
          <td>たんぱく質：</td><td><%= @protein %>g</td>
        </tr>
        <tr>
          <td>脂質：</td><td><%= @lipid %>g</td>
        </tr>
        <tr>
          <td>炭水化物：</td><td><%= @carbohydrate %>g</td>
        </tr>
        <tr>
          <td>塩分：</td><td><%= @salt %>g</td>
        </tr>
      </table>
    </h5>
  </div>
</div>