config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#index'

  # ゲストログイン用アクション
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  # sign_upでエラーが出た後、リロードでのエラー回避
    get 'users', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  # get 'users/mypage' => 'users#show'
  # get 'users/unsubscribe' => 'users#unsubscribe'
  # get 'recipes/search' => 'recipes#search'
  # patch 'users/withdraw' => 'users#withdraw'

  resources :users, only:[:edit,:update] do
    collection do
      get :mypage, action: :show
      get :unsubscribe
      patch :withdraw
    end
  end

  resources :recipes, only:[:new,:index,:show,:edit,:create,:update,:destroy] do
    collection do
      get :bookmarks
      get :search
    end
  end

  resources :units, only:[:index,:create,:destroy]
  resources :genres, only:[:index,:create,:destroy]
  resources :bookmarks, only:[:create,:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :recipes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_recipes, through: :bookmarks, source: :recipe

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲスト"
    end
  end

# 引数に渡されたものが、userのものであるか？
  def own?(object)
    id == object.user_id
  end

# # 引数に渡されたrecipeがブックマークされているか？
  def bookmark?(recipe)
    bookmark_recipes.include?(recipe)
  end

# # recipe_idを入れてブックマークする
#   def bookmark(recipe)
# # current_userがブックマークしているrecipeの配列にrecipeを入れる
#     bookmark_recipes << recipe
#   end

#   # 引数のrecipeのidをもつ、レコードを削除する
#   def unbookmark(recipe)
#     bookmark_recipes.destroy(recipe)
#   end

  # 公開ステータス
  def public_status
    if  status == false
      "非公開"
    else
      "公開"
    end
  end

  # def active_for_authentication?
  #   super && (is_active == true)
  # end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

# お試し機能中にユーザーの編集・削除を不可にする
  before_action :check_guest, only: :destroy

  def chrck_guest
    if resouce.email == 'guest@example.com'
      redirect_to root_path, alert: 'お試し機能中はユーザーの削除はできません'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

before_action :user_state, only: [:create]

# お試しログインの記述
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'お試し機能でログインしました'
  end

  private
    # 退会しているかを判断するメソッド
  def user_state
  #.処理1、入力されたemailからアカウント1件取得
    @user = User.find_by(email: params[:user][:email])
  # アカウントを取得出来なければ、メソッドを終了
    return if !@user
  # 処理2、取得したアカウントのパスワードと入力されたものが正しいか判別
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      flash[:notice] = "退会済みです。再度ご登録してご利用下さい。"
      redirect_to new_user_registration_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user

  def show
    @nickname = "#{@user.nickname}さんの編集ページ"
  end

  def edit
    @nickname = "#{@user.nickname}さんの編集ページ"
  end

  def update
    @user.update!(user_params)
    redirect_to mypage_users_path(@user)
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update!(is_active: false)
    reset_session
    flash[:notice] = "退会処理を完了いたしました。"
    redirect_to root_path
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:nickname,:is_active,:status,:email,:admin)
  end
end

app/views/users/edit.html.erb
<div class="container my-5">
  <div class="row ml-3">
    <div class="offset-1">
      <h1><%= @nickname %></h1>
    </div>
  </div>


  <%= form_with model: @user, url: user_path, method: :patch do |f| %>
      <div class="row mt-5 ml-5">
        <div class="col-10">

          <div class="form-group row">
            <%= f.label :"ニックネーム", class:"col-2"%>
            <%= f.text_field :nickname, autofocus: true, class: "form-control offset-1 col-4" %>
          </div>
          <div class="form-group row">
            <%= f.label :"メールアドレス", class:"col-2" %>
            <%= f.email_field :email, autocomplete: "email", class: "form-control offset-1 col-4" %>
          </div>
          <div class="form-group row">
            <%= f.label :"公開ステータス", class:"col-2" %>
            <label><%= f.radio_button :status, :false, class: "ml-5" %>非公開</label>
            <label><%= f.radio_button :status, :true, class: "ml-4" %>公開</label>
          </div>

          <div class="row actions">
            <%= f.submit "編集内容を保存", class:"btn btn-success offset-3 col-3 my-4" %>
            <%= link_to "退会する", unsubscribe_users_path(@user), class: "btn btn-danger offset-2 col-3 my-4" %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container my-5">
  <div class="row offset-1">
    <h1><%= @nickname %></h1>
  </div>
  <div class="row my-4">
    <h4 class="font-weight-bold ml-4 mr-5">登録情報</h4>
    <% if @user.email == 'guest@example.com' %>
    <% else %>
      <%= link_to "編集する", edit_user_path(@user), class:"btn btn-success text-white ml-5" %>
    <% end %>
  </div>

  <table class="table table-bordered col-8">
    <tr>
      <td class="col-2">ニックネーム</td>
      <td class="col-6">
        <%= @user.nickname %>
      </td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td>登録レシピ</td>
      <td><%= @user.recipes.count %>件</td>
    </tr>
    <tr>
      <td>公開ステータス</td>
      <td><%= @user.public_status %></td>
    </tr>
  </table>
</div>

app/views/users/unsubscribe.html.erb
<div class="container my-5">
  <div class="row my-5">
  </div>
  <div class="row my-5">
    <div class="col-12 text-center">
      <h3 class="font-weight-bold">本当に退会しますか？</h3>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-12 text-center">
      <h4>
        退会されますと、これまで登録したレシピや<br>
        お気に入りなど、すべてが閲覧できなくなります。<br>
        退会する場合は「退会する」をクリックしてください。
      </h4>
    </div>
  </div>


  <div class="row my-5">
    <div class="col-4 ml-4"></div>
      <%= link_to "退会しない", mypage_users_path(current_user), class:"btn btn-primary btn-lg" %>
      <%= link_to "退会する", withdraw_users_path(current_user), method: :patch, "data-confirm" => "本当に退会しますか？", class:"btn btn-danger btn-lg offset-1"  %>
    </div>
  </div>
</div>