config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#index'

  # ゲストログイン用アクション
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  # sign_upでエラーが出た後、リロードでのエラー回避
    get 'users', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  # get 'users/mypage' => 'users#show'
  # get 'users/unsubscribe' => 'users#unsubscribe'
  # get 'recipes/search' => 'recipes#search'
  # patch 'users/withdraw' => 'users#withdraw'

  resources :users, only:[:edit,:update] do
    collection do
      get :mypage, action: :show
      get :unsubscribe
      patch :withdraw
    end
  end

  resources :recipes, only:[:new,:index,:show,:edit,:create,:update,:destroy] do
    collection do
      get :bookmarks
      get :search
    end
  end

  resources :units, only:[:index,:create,:destroy]
  resources :genres, only:[:index,:create,:destroy]
  resources :bookmarks, only:[:create,:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/shared/_flash.html.erb
<!--レシピ登録時のエラーメッセージ-->
<% if flash[:notice] %>
  <p id='notice'>
    <%= flash[:notice] %>
  </p>
<% end %>
<% if @recipe.errors.any? %>
  <ul>
    <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_recipe_genre.html.erb
<table class="table table-hover">
  <% @recipes.each do |recipe| %>
    <tr class="font-weight-bold">
      <td class="col-2">
        <%= image_tag recipe.get_image(80,80) %>
      </td>
      <td class="col-6">
        <%= link_to recipe.cuisine_name, recipe_path(recipe.id)%>
      </td>
      <% if recipe.user.status %>
        <td class="col-4"><%= recipe.user.nickname %></td>
      <% else %>
        <td class="col-4">非公開</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/shared/_recipe_list.html.erb
<table class="table table-hover">
  <% @recipes.each do |recipe| %>
    <tr class="font-weight-bold">
      <td class="col-2">
        <%= image_tag recipe.get_image(100,100) %>
      </td>
      <td class="col-6">
        <%= link_to recipe.cuisine_name, recipe_path(recipe.id)%>
      </td>
      <% if recipe.user.status %>
        <td class="col-4"><%= recipe.user.nickname %></td>
      <% else %>
        <td class="col-4">非公開</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/shared/_search.html.erb
<%= search_form_for @q, url: search_recipes_path do |f| %>
<!--ジャンル選択フォーム-->
  <%= f.collection_select :genre_id_eq, @genres, :id, :name, :include_blank => '指定しない', class:'genre-select'  %>
<!--検索フォーム-->
  <%= f.search_field :cuisine_name_or_ingredients_name_cont, placeholder: 'レシピ名・食材名で探す', class:'input-box' %>
  <%= f.button type: "submit", class:"search-btn" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>