config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#index'

  # ゲストログイン用アクション
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  # sign_upでエラーが出た後、リロードでのエラー回避
    get 'users', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  # get 'users/mypage' => 'users#show'
  # get 'users/unsubscribe' => 'users#unsubscribe'
  # get 'recipes/search' => 'recipes#search'
  # patch 'users/withdraw' => 'users#withdraw'

  resources :users, only:[:edit,:update] do
    collection do
      get :mypage, action: :show
      get :unsubscribe
      patch :withdraw
    end
  end

  resources :recipes, only:[:new,:index,:show,:edit,:create,:update,:destroy] do
    collection do
      get :bookmarks
      get :search
    end
  end

  resources :units, only:[:index,:create,:destroy]
  resources :genres, only:[:index,:create,:destroy]
  resources :bookmarks, only:[:create,:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesCanApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand navbar-light", style ="background-color: #ffec47" >
        <div class="container">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png' %>
          <% end %>
          <ul class="navbar-nav ml-auto lead font-weight-bold">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", mypage_users_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "レシピ一覧", root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= render "shared/search", class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "トップページ", root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
      <span id="button">
        <% if current_user && current_user.admin? %>
          <div class="admin-button">
            <%= link_to  genres_path, class: 'btn btn-danger btn-lg' do %>
              <i class="fas fa-cog"></i>ジャンル編集
            <% end %>
          </div>
          <div class="admin-button my-4">
            <%= link_to  units_path, class: 'btn btn-danger btn-lg' do %>
              <i class="fas fa-cog"></i>単位編集
            <% end %>
          </div>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "+", new_recipe_path, class: 'btn btn-lg rounded-circle ml-auto shadow'%>
        <% end %>
      </span>
    </main>
    <footer class="footer text-black", style ="background-color: #ffec47;">
      <div class="container text-center mt-3">
        <h4>Recipes_can_app</h4>
      </div>
    </footer>
  </body>
</html>